# Full reference: https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v2beta18
kind: Config

portForward:
- resourceType: service
  resourceName: shellinabox
  port: 4200
  localPort: 4200

profiles:
  # profiles don't inherit values :(
  # the development profile
  - name: dev
    activation:
      - command: dev

    build:
      artifacts:
      - image: shellinabox

    deploy:
      kubectl:
        manifests:
        - manifests/*.yaml
