---
apiVersion: v1
kind: Service
metadata:
  name: shellinabox
spec:
  selector:
    app: shellinabox
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
---
# registry.ci.svc.cluster.local
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shellinabox
  labels:
    app: shellinabox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shellinabox
  template:
    metadata:
      labels:
        app: shellinabox
    spec:
      containers:
        - image: shellinabox
          name: shellinabox
          imagePullPolicy: IfNotPresent
          env:
            - name: USERNAME
              value: "bob"
            - name: PASSWORD
              value: "8675309"
          ports:
            - containerPort: 4200
